-- MySQL Script generated by MySQL Workbench
-- Sun Oct  2 17:38:00 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema vilicapasDB
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema 2ucase_bd3
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema 2ucase_bd3
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `2ucase_bd3` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ;
-- -----------------------------------------------------
-- Schema 2ucase_bd2
-- -----------------------------------------------------

-- -----------------------------------------------------
USE `2ucase_bd3` ;

-- -----------------------------------------------------
-- Table `2ucase_bd3`.`adm_administrador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `2ucase_bd3`.`adm_administrador` (
  `id_adm` INT NOT NULL AUTO_INCREMENT,
  `nome_adm` VARCHAR(300) NOT NULL COMMENT 'nome do administrador',
  `email_adm` VARCHAR(300) NOT NULL COMMENT 'email do administrador',
  `senha_adm` VARCHAR(64) NOT NULL COMMENT 'senha em sha256',
  `poder_adm` INT(1) NOT NULL COMMENT 'abrangencia do usuario no sistema',
  `status` INT(1) NOT NULL COMMENT '1 - ativo; 0 - inativo',
  `data_reg_adm` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'data e hora do registro',
  PRIMARY KEY (`id_adm`));


-- -----------------------------------------------------
-- Table `2ucase_bd3`.`adm_menu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `2ucase_bd3`.`adm_menu` (
  `id_menu` INT NOT NULL AUTO_INCREMENT,
  `nome_menu` VARCHAR(300) NOT NULL,
  `link_menu` VARCHAR(300) NOT NULL,
  `status` INT(1) NOT NULL COMMENT '1 - ativo; 0 - inativo',
  `data_reg_menu` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'data e hora do registro',
  PRIMARY KEY (`id_menu`));


-- -----------------------------------------------------
-- Table `2ucase_bd3`.`adm_carrossel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `2ucase_bd3`.`adm_carrossel` (
  `id_carrossel` INT NOT NULL AUTO_INCREMENT,
  `nome_carrossel` VARCHAR(200) NOT NULL,
  `link_carrossel` VARCHAR(300) NOT NULL,
  `status` INT(1) NOT NULL COMMENT '1 - ativo; 0 - inativo',
  `data_reg_adm` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'data e hora do registro',
  PRIMARY KEY (`id_carrossel`));


-- -----------------------------------------------------
-- Table `2ucase_bd3`.`user_mod_celular`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `2ucase_bd3`.`user_mod_celular` (
  `id_modelo_celular` INT NOT NULL AUTO_INCREMENT,
  `marca_celular` VARCHAR(64) NOT NULL,
  `modelo_celular` VARCHAR(300) NOT NULL,
  PRIMARY KEY (`id_modelo_celular`));


-- -----------------------------------------------------
-- Table `2ucase_bd3`.`user_forma_pagamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `2ucase_bd3`.`user_forma_pagamento` (
  `id_pagamento` INT NOT NULL AUTO_INCREMENT,
  `parcelamento_pagamento` INT(1) NOT NULL,
  `metodo_pagamento` VARCHAR(120) NOT NULL,
  PRIMARY KEY (`id_pagamento`));


-- -----------------------------------------------------
-- Table `2ucase_bd3`.`user_cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `2ucase_bd3`.`user_cliente` (
  `id_cliente` INT NOT NULL AUTO_INCREMENT,
  `nome_cliente` VARCHAR(300) NOT NULL COMMENT 'nome do cliente',
  `email_cliente` VARCHAR(300) NOT NULL COMMENT 'email do cliente',
  `cpf_cliente` VARCHAR(18) NOT NULL COMMENT 'cpf do cliente',
  `telefone_cliente` VARCHAR(18) NOT NULL COMMENT 'telefone do cliente',
  `genero_cliente` INT(1) NOT NULL COMMENT '1 - feminino; 0 - masculino; 2 - não informar',
  `senha_cliente` VARCHAR(256) NOT NULL COMMENT 'senha em sha256',
  `data_nasc_cliente` DATE NOT NULL COMMENT 'data de nascimente',
  `data_reg_cliente` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'data e hora do registro',
  `status` INT(1) NOT NULL COMMENT '1 - ativo; 0 - inativo',
  PRIMARY KEY (`id_cliente`)
);


-- -----------------------------------------------------
-- Table `2ucase_bd3`.`user_endereco_cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `2ucase_bd3`.`user_endereco_cliente` (
  `id_endereco` INT NOT NULL AUTO_INCREMENT,
  `id_cliente` INT NOT NULL,
  `logradouro_cliente` VARCHAR(900) NOT NULL,
  `bairro_cliente` VARCHAR(100) NOT NULL,
  `cep_cliente` VARCHAR(15) NOT NULL,
  `uf_cliente` VARCHAR(2) NOT NULL,
  `numero_cliente` INT(5) NOT NULL,
  `complemento_cliente` VARCHAR(150) NULL DEFAULT NULL,
  `ponto_ref_cliente` VARCHAR(300) NULL DEFAULT NULL,
  `data_endereco_cliente` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'data e hora do registro',
  PRIMARY KEY (`id_endereco`),
  CONSTRAINT `fk_id_cliente`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `2ucase_bd3`.`user_cliente` (`id_cliente`)
    ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table `2ucase_bd3`.`adm_submenu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `2ucase_bd3`.`adm_submenu` (
  `id_submenu` INT NOT NULL AUTO_INCREMENT,
  `id_menu` INT NOT NULL,
  `nome_submenu` VARCHAR(300) NOT NULL,
  `link_submenu` VARCHAR(300) NOT NULL,
  `status` INT(1) NOT NULL COMMENT '1 - ativo; 0 - inativo',
  `data_reg_submenu` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'data e hora do registro',
  PRIMARY KEY (`id_submenu`),
  CONSTRAINT `fk_id_menu`
    FOREIGN KEY (`id_menu`)
    REFERENCES `2ucase_bd3`.`adm_menu` (`id_menu`)
    ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table `2ucase_bd3`.`user_categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `2ucase_bd3`.`user_categoria` (
  `id_categoria` INT NOT NULL AUTO_INCREMENT,
  `nome_categoria` VARCHAR(200) NOT NULL,
  `img_categoria` VARCHAR(300) NOT NULL,
  `data_reg_cupom` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'data e hora do registro',
  `link_categoria` VARCHAR(300) NOT NULL,
  PRIMARY KEY (`id_categoria`));


-- -----------------------------------------------------
-- Table `2ucase_bd3`.`user_produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `2ucase_bd3`.`user_produto` (
  `id_produto` INT NOT NULL AUTO_INCREMENT,
  `id_modelo_celular` INT NOT NULL,
  `id_categoria` INT NOT NULL,
  `nome_produto` VARCHAR(300) NOT NULL,
  `preco_produto` DECIMAL NOT NULL,
  `descricao_produto` VARCHAR(900) NOT NULL,
  `imagem_principal_produto` VARCHAR(300) NOT NULL,
  `quantidade_produto` INT NOT NULL,
  `categoria_special_produto` VARCHAR(200) NOT NULL,
  `garantias_produto` VARCHAR(300) NOT NULL COMMENT 'beneficios - ex - garantia 3 dias',
  `status` INT(1) NOT NULL COMMENT '2 - oferta 1 - disponivel 0 - indisponivel',
  `data_reg_produto` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'data e hora do registro',
  PRIMARY KEY (`id_produto`),
  CONSTRAINT `fk_id_modelo_celular`
    FOREIGN KEY (`id_modelo_celular`)
    REFERENCES `2ucase_bd3`.`user_mod_celular` (`id_modelo_celular`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_id_categoria`
    FOREIGN KEY (`id_categoria`)
    REFERENCES `2ucase_bd3`.`user_categoria` (`id_categoria`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table `2ucase_bd3`.`user_produtos_img`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `2ucase_bd3`.`user_produtos_img` (
  `id_img` INT NOT NULL AUTO_INCREMENT,
  `id_produto` INT NOT NULL,
  `nome_img` VARCHAR(300) NOT NULL,
  `link_img` VARCHAR(300) NOT NULL,
  `status` INT(1) NOT NULL COMMENT '1 - ativo; 0 - inativo',
  `data_reg_img` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'data e hora do registro',
  PRIMARY KEY (`id_img`),
  CONSTRAINT `fk_id_produto`
    FOREIGN KEY (`id_produto`)
    REFERENCES `2ucase_bd3`.`user_produto` (`id_produto`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table `2ucase_bd3`.`user_cupom`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `2ucase_bd3`.`user_cupom` (
  `id_cupom` INT NOT NULL AUTO_INCREMENT,
  `id_categoria` INT NOT NULL,
  `nome_cupom` INT NOT NULL,
  `codigo_cupom` VARCHAR(200) NOT NULL,
  `data_expira_cupom` DATE NOT NULL,
  `desconto_cupom` DECIMAL NOT NULL,
  `data_reg_cupom` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'data e hora do registro',
  `status` INT(1) NOT NULL COMMENT '1 - ativo; 0 - inativo',
  PRIMARY KEY (`id_cupom`),
  CONSTRAINT `fk1_id_categoria`
    FOREIGN KEY (`id_categoria`)
    REFERENCES `2ucase_bd3`.`user_categoria` (`id_categoria`));


-- -----------------------------------------------------
-- Table `2ucase_bd2`.`venda_status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `2ucase_bd2`.`venda_status` (
  `id_status` INT NOT NULL AUTO_INCREMENT,
  `status_venda` VARCHAR(60) NOT NULL,
  `data_reg_status` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_status`));

-- -----------------------------------------------------
-- Table `2ucase_bd2`.`user_carrinho`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `2ucase_bd2`.`user_carrinho` (
  `id_carrinho` INT NOT NULL AUTO_INCREMENT,
  `data_reg_carrinho` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `id_cliente` INT NOT NULL,
  `total_carrinho` DECIMAL NOT NULL,
  `desconto_carrinho` DECIMAL NOT NULL,
  `quant_carrinho` INT NOT NULL,
  `id_endereco` INT NOT NULL,
  `frete_carrinho` DECIMAL NOT NULL,
  PRIMARY KEY (`id_carrinho`),
  CONSTRAINT `fk_user_carrinho_user_cliente`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `2ucase_bd3`.`user_cliente` (`id_cliente`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_user_carrinho_user_endereco_cliente1`
    FOREIGN KEY (`id_endereco`)
    REFERENCES `2ucase_bd3`.`user_endereco_cliente` (`id_endereco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

-- -----------------------------------------------------
-- Table `2ucase_bd3`.`adm_venda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `2ucase_bd3`.`adm_venda` (
  `id_venda` INT NOT NULL AUTO_INCREMENT,
  `id_cliente` INT NOT NULL,
  `id_pagamento` INT NOT NULL,
  `valor_desconto_total` DOUBLE NOT NULL,
  `data_venda` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'data e hora do registro',
  `valor_venda_total` DOUBLE NOT NULL,
  `quant_produto_total` INT NOT NULL,
  `id_status` INT NOT NULL,
  `id_carrinho` INT NOT NULL,
  PRIMARY KEY (`id_venda`),
  CONSTRAINT `fk_id_pagamento`
    FOREIGN KEY (`id_pagamento`)
    REFERENCES `2ucase_bd3`.`user_forma_pagamento` (`id_pagamento`)
    ON UPDATE CASCADE,
  CONSTRAINT `fk1_id_cliente`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `2ucase_bd3`.`user_cliente` (`id_cliente`)
    ON UPDATE CASCADE,
  CONSTRAINT `fk_adm_venda_venda_status1`
    FOREIGN KEY (`id_status`)
    REFERENCES `2ucase_bd2`.`venda_status` (`id_status`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_adm_venda_user_carrinho1`
    FOREIGN KEY (`id_carrinho`)
    REFERENCES `2ucase_bd2`.`user_carrinho` (`id_carrinho`)
    ON DELETE NO ACTION
    ON UPDATE RESTRICT);


-- -----------------------------------------------------
-- Table `2ucase_bd3`.`user_avaliacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `2ucase_bd3`.`user_avaliacao` (
  `id_avaliacao` INT NOT NULL AUTO_INCREMENT,
  `id_produto` INT NOT NULL,
  `id_cliente` INT NOT NULL,
  `nota_avaliacao` INT(1) NOT NULL COMMENT 'avaliação de 1 - 5',
  `titulo_avaliacao` VARCHAR(300) NOT NULL,
  `descricao` VARCHAR(900) NOT NULL,
  `data_avaliacao` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'data e hora do registro',
  `status` INT(1) NOT NULL COMMENT '1 - ativo; 0 - inativo',
  PRIMARY KEY (`id_avaliacao`),
  CONSTRAINT `fk1_id_produto`
    FOREIGN KEY (`id_produto`)
    REFERENCES `2ucase_bd3`.`user_produto` (`id_produto`)
    ON UPDATE CASCADE,
  CONSTRAINT `fk2_id_cliente`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `2ucase_bd3`.`user_cliente` (`id_cliente`)
    ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table `2ucase_bd3`.`produto_carrinho`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `2ucase_bd3`.`produto_carrinho` (
  `id_produto_carrinho` INT NOT NULL AUTO_INCREMENT,
  `id_carrinho` INT NOT NULL,
  `id_produto` INT NOT NULL,
  `quant_carrinho` INT NOT NULL,
  `preco_quant_prod` DECIMAL NOT NULL,
  `preco_desconto_prod` DECIMAL NOT NULL,
  `data_reg_Cprod` DATETIME NOT NULL,
  PRIMARY KEY (`id_produto_carrinho`),
  CONSTRAINT `fk_produto_carrinho_user_carrinho1`
    FOREIGN KEY (`id_carrinho`)
    REFERENCES `2ucase_bd2`.`user_carrinho` (`id_carrinho`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_produto_carrinho_user_produto1`
    FOREIGN KEY (`id_produto`)
    REFERENCES `2ucase_bd3`.`user_produto` (`id_produto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
