-- MySQL Script generated by MySQL Workbench
-- Sun Oct  2 17:38:00 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema vilicapasDB
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema 2ucase_bd3
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema 2ucase_bd3
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `2ucase_bd3` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ;
-- -----------------------------------------------------
-- Schema 2ucase_bd3
-- -----------------------------------------------------

-- -----------------------------------------------------
USE `2ucase_bd3` ;
-- -----------------------------------------------------
create table adm_administrador
(
    id_adm       int auto_increment
        primary key,
    nome_adm     varchar(300)                         not null comment 'nome do administrador',
    email_adm    varchar(300)                         not null comment 'email do administrador',
    senha_adm    varchar(64)                          not null comment 'senha em sha256',
    poder_adm    int(1)                               not null comment 'abrangencia do usuario no sistema',
    status       int(1)                               not null comment '1 - ativo; 0 - inativo',
    data_reg_adm datetime default current_timestamp() not null comment 'data e hora do registro'
);

create table adm_carrossel
(
    id_carrossel         int auto_increment
        primary key,
    nome_carrossel       varchar(200)                         not null,
    link_carrossel       varchar(300)                         not null,
    status               int(1)                               not null comment '1 - ativo; 0 - inativo',
    data_reg_adm         datetime default current_timestamp() not null comment 'data e hora do registro',
    link_promo_carrossel varchar(300)                         not null
);

create table adm_menu
(
    id_menu       int auto_increment
        primary key,
    nome_menu     varchar(300)                         not null,
    link_menu     varchar(300)                         not null,
    status        int(1)                               not null comment '1 - ativo; 0 - inativo',
    data_reg_menu datetime default current_timestamp() not null comment 'data e hora do registro'
);

create table adm_submenu
(
    id_submenu       int auto_increment
        primary key,
    id_menu          int                                  not null,
    nome_submenu     varchar(300)                         not null,
    link_submenu     varchar(300)                         not null,
    status           int(1)                               not null comment '1 - ativo; 0 - inativo',
    data_reg_submenu datetime default current_timestamp() not null comment 'data e hora do registro',
    constraint fk_id_menu
        foreign key (id_menu) references adm_menu (id_menu)
            on update cascade
);

create table user_categoria
(
    id_categoria   int auto_increment
        primary key,
    nome_categoria varchar(200)                         not null,
    img_categoria  varchar(300)                         not null,
    data_reg_cupom datetime default current_timestamp() not null comment 'data e hora do registro',
    link_categoria varchar(300)                         not null
);

create table user_cliente
(
    id_cliente           int auto_increment
        primary key,
    nome_cliente         varchar(300)                         not null comment 'nome do cliente',
    email_cliente        varchar(300)                         not null comment 'email do cliente',
    cpf_cliente          varchar(18)                          not null comment 'cpf do cliente',
    telefone_cliente     varchar(18)                          not null comment 'telefone do cliente',
    genero_cliente       int(1)                               not null comment '1 - feminino; 0 - masculino; 2 - n?o informar',
    senha_cliente        varchar(256)                         not null comment 'senha em sha256',
    data_nasc_cliente    date                                 not null comment 'data de nascimente',
    data_reg_cliente     datetime default current_timestamp() not null comment 'data e hora do registro',
    status               int(1)                               not null comment '1 - ativo; 0 - inativo',
    telefoneFixo_cliente varchar(16)                          not null,
    token_email          varchar(60)                          not null
);

create table user_cupom
(
    id_cupom          int auto_increment
        primary key,
    id_categoria      int                                  not null,
    nome_cupom        varchar(400)                         not null,
    codigo_cupom      varchar(200)                         not null,
    data_expira_cupom date                                 not null,
    desconto_cupom    float                                not null,
    data_reg_cupom    datetime default current_timestamp() not null comment 'data e hora do registro',
    status            int(1)                               not null comment '1 - ativo; 0 - inativo',
    constraint fk1_id_categoria
        foreign key (id_categoria) references user_categoria (id_categoria)
);

create table user_endereco_cliente
(
    id_endereco           int auto_increment
        primary key,
    id_cliente            int                                  not null,
    logradouro_cliente    varchar(900)                         not null,
    bairro_cliente        varchar(100)                         not null,
    cep_cliente           varchar(15)                          not null,
    uf_cliente            varchar(2)                           not null,
    numero_cliente        int(5)                               not null,
    complemento_cliente   varchar(150)                         null,
    ponto_ref_cliente     varchar(300)                         null,
    data_endereco_cliente datetime default current_timestamp() not null comment 'data e hora do registro',
    nomeR_cliente         varchar(250)                         not null,
    cidade_cliente        varchar(250)                         not null,
    constraint fk_id_cliente
        foreign key (id_cliente) references user_cliente (id_cliente)
            on update cascade
);

create table user_forma_pagamento
(
    id_pagamento           int auto_increment
        primary key,
    parcelamento_pagamento int(1)       not null,
    metodo_pagamento       varchar(120) not null
);

create table user_mod_celular
(
    id_modelo_celular int auto_increment
        primary key,
    marca_celular     varchar(64)  not null,
    modelo_celular    varchar(300) not null
);

create table user_produto
(
    id_produto                int auto_increment
        primary key,
    id_modelo_celular         int                                        not null,
    id_categoria              int                                        not null,
    nome_produto              varchar(300)                               not null,
    preco_produto             decimal(10, 2) default 0.00                not null,
    descricao_produto         varchar(900)                               not null,
    imagem_principal_produto  varchar(300)                               not null,
    quantidade_produto        int                                        not null,
    categoria_special_produto varchar(200)                               not null,
    garantias_produto         varchar(300)                               not null comment 'beneficios - ex - garantia 3 dias',
    status                    int(1)                                     not null comment '2 - oferta 1 - disponivel 0 - indisponivel',
    data_reg_produto          datetime       default current_timestamp() not null comment 'data e hora do registro',
    cod_produto               int(4) unsigned zerofill                   not null,
    peso_produto              int                                        not null comment 'Peso em Gramas',
    last_price_produto        decimal(10, 2) default 0.00                not null comment 'Ultimo preço do produto, só add caso a categoria dele for promoção',
    constraint fk_id_categoria
        foreign key (id_categoria) references user_categoria (id_categoria)
            on update cascade,
    constraint fk_id_modelo_celular
        foreign key (id_modelo_celular) references user_mod_celular (id_modelo_celular)
            on update cascade
);

create table user_avaliacao
(
    id_avaliacao     int auto_increment
        primary key,
    id_produto       int                                  not null,
    id_cliente       int                                  not null,
    nota_avaliacao   int(1)                               not null comment 'avalia??o de 1 - 5',
    titulo_avaliacao varchar(300)                         not null,
    descricao        varchar(900)                         not null,
    data_avaliacao   datetime default current_timestamp() not null comment 'data e hora do registro',
    status           int(1)                               not null comment '1 - ativo; 0 - inativo',
    constraint fk1_id_produto
        foreign key (id_produto) references user_produto (id_produto)
            on update cascade,
    constraint fk2_id_cliente
        foreign key (id_cliente) references user_cliente (id_cliente)
            on update cascade
);

create table user_favoritos
(
    id_favoritos      int auto_increment
        primary key,
    id_produto        int                                   not null,
    id_cliente        int                                   not null,
    dataReg_favoritos timestamp default current_timestamp() not null,
    constraint user_favoritos_user_cliente_id_cliente_fk
        foreign key (id_cliente) references user_cliente (id_cliente)
            on update cascade on delete cascade,
    constraint user_favoritos_user_produto_id_produto_fk
        foreign key (id_produto) references user_produto (id_produto)
            on update cascade on delete cascade
);

create table user_produtos_img
(
    id_img       int auto_increment
        primary key,
    id_produto   int                                  not null,
    nome_img     varchar(300)                         not null,
    link_img     varchar(300)                         not null,
    status       int(1)                               not null comment '1 - ativo; 0 - inativo',
    data_reg_img datetime default current_timestamp() not null comment 'data e hora do registro',
    constraint fk_id_produto
        foreign key (id_produto) references user_produto (id_produto)
            on update cascade on delete cascade
);

create table venda_status
(
    id_status       int auto_increment
        primary key,
    status_venda    varchar(60)                          not null,
    data_reg_status datetime default current_timestamp() not null
);

create table user_carrinho
(
    id_carrinho       int auto_increment
        primary key,
    data_reg_carrinho datetime       default current_timestamp() not null,
    id_cliente        int                                        not null,
    total_carrinho    decimal(10, 2) default 0.00                not null,
    desconto_carrinho decimal(10, 2) default 0.00                not null,
    quant_carrinho    int                                        not null,
    id_status         int                                        not null,
    constraint fk_user_carrinho_user_cliente
        foreign key (id_cliente) references user_cliente (id_cliente)
            on update cascade on delete cascade,
    constraint id_fk_status
        foreign key (id_status) references venda_status (id_status)
);

create table adm_venda
(
    id_venda             int auto_increment
        primary key,
    id_cliente           int                                        not null,
    id_pagamento         int                                        not null,
    valor_desconto_total double                                     not null,
    data_venda           datetime       default current_timestamp() not null comment 'data e hora do registro',
    valor_venda_total    decimal(10, 2) default 0.00                not null,
    quant_produto_total  int                                        not null,
    id_status            int                                        not null,
    id_carrinho          int                                        not null,
    numero_venda         int                                        not null,
    frete_carrinho       decimal(10, 2) default 0.00                not null,
    id_endereco          int                                        not null,
    cod_frete_venda      varchar(10)    default '0'                 not null,
    constraint fk1_id_cliente
        foreign key (id_cliente) references user_cliente (id_cliente)
            on update cascade,
    constraint fk_adm_venda_user_carrinho1
        foreign key (id_carrinho) references user_carrinho (id_carrinho),
    constraint fk_adm_venda_venda_status1
        foreign key (id_status) references venda_status (id_status)
            on update cascade,
    constraint fk_id_pagamento
        foreign key (id_pagamento) references user_forma_pagamento (id_pagamento)
            on update cascade,
    constraint id_fk_endereco
        foreign key (id_endereco) references user_endereco_cliente (id_endereco)
);

create table produto_carrinho
(
    id_produto_carrinho int auto_increment
        primary key,
    id_carrinho         int                                        not null,
    id_produto          int                                        not null,
    quant_carrinho      int                                        not null,
    preco_quant_prod    decimal(10, 2) default 0.00                not null,
    preco_desconto_prod decimal(10, 2) default 0.00                not null comment 'So ira receber um valor, quando aplicado o cupom
VALOR: Porcentagem do cupom menos o valor do produto.',
    data_reg_Cprod      datetime       default current_timestamp() not null,
    marca_celular       varchar(120)                               not null,
    preco_total         decimal(10, 2) default 0.00                not null comment 'Valor da quantidade do produto menos o valor com o desconto',
    used_cupom          int            default 0                   not null comment '1 Utilizou
0 Não utilizou',
    constraint fk_produto_carrinho_user_carrinho1
        foreign key (id_carrinho) references user_carrinho (id_carrinho),
    constraint fk_produto_carrinho_user_produto1
        foreign key (id_produto) references user_produto (id_produto)
);


create table `2ucase_bd3`.user_newsletter
(
    id_noticias       int auto_increment
        primary key,
    email_noticias    varchar(360)                          not null,
    data_reg_noticias timestamp default current_timestamp() not null comment 'Data de registro'
);




-- INSERTS CATEGORIA

INSERT INTO user_categoria (nome_categoria, img_categoria, link_categoria) VALUES ('Times', '../assets/img/times-category.jpg', './homepage.php');
INSERT INTO user_categoria (nome_categoria, img_categoria, link_categoria) VALUES ( 'Animacoes', '../assets/img/animacao-category.jpg', './homepage.php');
INSERT INTO user_categoria (nome_categoria, img_categoria, link_categoria) VALUES ( 'flork', '../assets/img/flork-category.jpg', './homepage.php');
INSERT INTO user_categoria (nome_categoria, img_categoria, link_categoria) VALUES ( 'estampas', '../assets/img/estampa-category.jpg', './homepage.php');
INSERT INTO user_categoria (nome_categoria, img_categoria, link_categoria) VALUES ( 'herois', '../assets/img/herois-category.jpg', './homepage.php');
-- NAO ENCONTREI IMAGEM POP SOCKET
INSERT INTO user_categoria (nome_categoria, img_categoria, link_categoria) VALUES ( 'pop-socket', '../assets/img/StitchAirpodscase.png', './homepage.php');





-- INSERT INTO MODELO CELULAR

INSERT INTO user_mod_celular (marca_celular, modelo_celular) VALUES ('Apple', 'Iphone 13 Pro Max');
INSERT INTO user_mod_celular (marca_celular, modelo_celular) VALUES ('Apple', 'Iphone 12');
INSERT INTO user_mod_celular (marca_celular, modelo_celular) VALUES ('Apple', 'Iphone 11');


-- INSERT INTO VENDA STATUS

INSERT INTO venda_status (status_venda) VALUES ('Pendente');
INSERT INTO venda_status (status_venda) VALUES ('Pagamento Aprovado');
INSERT INTO venda_status (status_venda) VALUES ('Cancelada');
INSERT INTO venda_status (status_venda) VALUES ('Enviada');
INSERT INTO venda_status (status_venda) VALUES ('Entregue');
INSERT INTO venda_status (status_venda) VALUES ('Reembolsada');


-- INSERT INTO FORMA PAGAMENTO

INSERT INTO user_forma_pagamento (parcelamento_pagamento, metodo_pagamento)
VALUES (5, 'Cartão de Crédito');

INSERT INTO user_forma_pagamento (parcelamento_pagamento, metodo_pagamento)
VALUES (0, 'Cartão de Debito');

INSERT INTO user_forma_pagamento (parcelamento_pagamento, metodo_pagamento)
VALUES (0, 'Boleto');

INSERT INTO user_forma_pagamento (parcelamento_pagamento, metodo_pagamento)
VALUES (0, 'PIX');



SELECT
-- TABELA ADM VENDA

adm_venda.id_venda, adm_venda.id_cliente, adm_venda.id_pagamento, adm_venda.valor_desconto_total,
adm_venda.data_venda, adm_venda.valor_venda_total, adm_venda.quant_produto_total,
adm_venda.id_status, adm_venda.id_carrinho,

-- TABELA STATUS VENDA
venda_status.status_venda,

--  TABELA USER CARRINHO
user_carrinho.data_reg_carrinho, user_carrinho.total_carrinho, user_carrinho.desconto_carrinho,
user_carrinho.quant_carrinho, user_carrinho.id_endereco, user_carrinho.frete_carrinho,

--  TABELA USER CLIENTE
user_cliente.nome_cliente, user_cliente.email_cliente, user_cliente.cpf_cliente,
user_cliente.telefone_cliente, user_cliente.genero_cliente, user_cliente.data_nasc_cliente,
user_cliente.status,

--  TABELA USER ENDERECO CLIENTE
user_endereco_cliente.logradouro_cliente, user_endereco_cliente.bairro_cliente,
user_endereco_cliente.cep_cliente, user_endereco_cliente.uf_cliente,
user_endereco_cliente.numero_cliente, user_endereco_cliente.complemento_cliente,
user_endereco_cliente.ponto_ref_cliente

FROM adm_venda

         INNER JOIN venda_status
                    ON adm_venda.id_status = venda_status.id_status

         INNER JOIN user_carrinho
                    ON adm_venda.id_carrinho = user_carrinho.id_carrinho

         INNER JOIN user_cliente
                    ON adm_venda.id_cliente = user_cliente.id_cliente

         INNER JOIN user_endereco_cliente
                    ON user_carrinho.id_endereco = user_endereco_cliente.id_endereco
WHERE adm_venda.id_venda = :id;

